#################################################################
# bcl2fastq
#
# :Parameters:
#
# - do:    if unchecked, this rule is ignored
# - database_directory: select a directory with a kraken database
#   Please see sequana documentation for details
#
#   intensities are expected to be found in input_directory/Data/Intensities
#   Base call data are to be found in input_directory/Data/Intensities/BaseCalls

input_directory: "%(input_directory)s"


bcl2fastq:
    threads: 4
    barcode_mismatch: 0
    sample_sheet_file: "SampleSheet.csv"
    output_directory: "fastq"
    #input_directory: "20190207_FS10000482_2_BPA73010-1129"
    ignore_missing_controls: true
    ignore_missing_bcls: true
    no_bgzf_compression: true
    #intensities_directory: "Data/Intensities"
    #runfolder_directory: 
    options: ""
